config/routes.rb
Rails.application.routes.draw do  

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles

  resources :classsifieds

  resources :zipcodes

  devise_for :admins
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/products'

  get 'welcome/advertise'

  get 'welcome/login'

  get 'welcome/register'



  root to: 'articles#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/classsified.rb
class Classsified < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order("created_at DESC")
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, notice: "The article has been successfully created."
    else
      render action: "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to articles_path, notice: "The article has been successfully updated."
    else
      render action: "edit"
    end
  end

private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/classsifieds_controller.rb
class ClasssifiedsController < ApplicationController
  before_action :set_classsified, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @classsifieds = Classsified.all
    respond_with(@classsifieds)
  end

  def show
    respond_with(@classsified)
  end

  def new
    @classsified = Classsified.new
    respond_with(@classsified)
  end

  def edit
  end

  def create
    @classsified = Classsified.new(classsified_params)
    @classsified.save
    respond_with(@classsified)
  end

  def update
    @classsified.update(classsified_params)
    respond_with(@classsified)
  end

  def destroy
    @classsified.destroy
    respond_with(@classsified)
  end

  private
    def set_classsified
      @classsified = Classsified.find(params[:id])
    end

    def classsified_params
      params.require(:classsified).permit(:title, :postedDate, :details, :expireDate, :categoryid, :contactId, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def products
  end

  def advertise
  end

  def login
  end

  def register
  end
end

app/controllers/zipcodes_controller.rb
class ZipcodesController < ApplicationController
  before_action :set_zipcode, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @zipcodes = Zipcode.all
    respond_with(@zipcodes)
  end

  def show
    respond_with(@zipcode)
  end

  def new
    @zipcode = Zipcode.new
    respond_with(@zipcode)
  end

  def edit
  end

  def create
    @zipcode = Zipcode.new(zipcode_params)
    @zipcode.save
    respond_with(@zipcode)
  end

  def update
    @zipcode.update(zipcode_params)
    respond_with(@zipcode)
  end

  def destroy
    @zipcode.destroy
    respond_with(@zipcode)
  end

  private
    def set_zipcode
      @zipcode = Zipcode.find(params[:id])
    end

    def zipcode_params
      params.require(:zipcode).permit(:details, :zip, :countOfCity, :cityStName, :lastLineCity, :state, :county, :lat_degree, :lon_degree, :lat, :long, :areacode, :timeZoneLabel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/classsifieds_helper.rb
module ClasssifiedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/zipcodes_helper.rb
module ZipcodesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <ul>
    <%= @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @article do |f| %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
  </div>
  <div>
    <%= f.cktext_area :body, rows: 10 %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= "Editing #{@article.title}" %>
<%= render "form" %>

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path %>
<% @articles.each do |article| %>
  <h3><%= article.title.html_safe %></h3>
  <p><%= article.body.html_safe %></p>
  <%= link_to "Edit Article", edit_article_path(article) %>
  <% if article != @articles.last %>
  <hr />
  <% end %>
<% end %>

app/views/articles/new.html.erb
<h3> New Article</h3>
<%= render "form" %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong><%= @article.title %></strong>
  
</p>

<p>
  
  <%= render html:@article.body %>
</p>

app/views/classsifieds/_form.html.erb
<%= form_for(@classsified) do |f| %>
  <% if @classsified.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classsified.errors.count, "error") %> prohibited this classsified from being saved:</h2>

      <ul>
      <% @classsified.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :postedDate %><br>
    <%= f.date_select :postedDate %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :expireDate %><br>
    <%= f.date_select :expireDate %>
  </div>
  <div class="field">
    <%= f.label :categoryid %><br>
    <%= f.number_field :categoryid %>
  </div>
  <div class="field">
    <%= f.label :contactId %><br>
    <%= f.number_field :contactId %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classsifieds/edit.html.erb
<h1>Editing classsified</h1>

<%= render 'form' %>

<%= link_to 'Show', @classsified %> |
<%= link_to 'Back', classsifieds_path %>

app/views/classsifieds/index.html.erb
<h1>Listing classsifieds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Posteddate</th>
      <th>Details</th>
      <th>Expiredate</th>
      <th>Categoryid</th>
      <th>Contactid</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classsifieds.each do |classsified| %>
      <tr>
        <td><%= classsified.title %></td>
        <td><%= classsified.postedDate %></td>
        <td><%= classsified.details %></td>
        <td><%= classsified.expireDate %></td>
        <td><%= classsified.categoryid %></td>
        <td><%= classsified.contactId %></td>
        <td><%= classsified.status %></td>
        <td><%= link_to 'Show', classsified %></td>
        <td><%= link_to 'Edit', edit_classsified_path(classsified) %></td>
        <td><%= link_to 'Destroy', classsified, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classsified', new_classsified_path %>

app/views/classsifieds/new.html.erb
<h1>New classsified</h1>

<%= render 'form' %>

<%= link_to 'Back', classsifieds_path %>

app/views/classsifieds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @classsified.title %>
</p>

<p>
  <strong>Posteddate:</strong>
  <%= @classsified.postedDate %>
</p>

<p>
  <strong>Details:</strong>
  <%= @classsified.details %>
</p>

<p>
  <strong>Expiredate:</strong>
  <%= @classsified.expireDate %>
</p>

<p>
  <strong>Categoryid:</strong>
  <%= @classsified.categoryid %>
</p>

<p>
  <strong>Contactid:</strong>
  <%= @classsified.contactId %>
</p>

<p>
  <strong>Status:</strong>
  <%= @classsified.status %>
</p>

<%= link_to 'Edit', edit_classsified_path(@classsified) %> |
<%= link_to 'Back', classsifieds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Market</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- Menu -->

	  <div class="container">
    <ul class="nav nav-tabs">
    <li>  <%= link_to "Home" , root_path %></li>
    <li>   <%= link_to "About Us" , welcome_about_path %></li>
    <li>   <%= link_to "Products" , welcome_products_path %></li>
    <li> <%= link_to "Register" , welcome_register_path %></li>
    <li>  <%= link_to "LogIn" , welcome_login_path %></li>
    </ul>
    
    <p class="notice"> <%= notice %> </p>
    <p class="alert"> <%= alert %> </p>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
<div align="center">
	<p>
		&copy; Copyright 1997 - 2015 Bizovation, LLC.<br />
		All rights reserved.
	</p>
 </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/advertise.html.erb
<h1>Welcome#advertise</h1>
<p>Find me in app/views/welcome/advertise.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/login.html.erb
<h1>Welcome#login</h1>
<p>Find me in app/views/welcome/login.html.erb</p>

app/views/welcome/products.html.erb
<h1>Welcome#products</h1>
<p>Find me in app/views/welcome/products.html.erb</p>

app/views/welcome/register.html.erb
<h1>Welcome#register</h1>
<p>Find me in app/views/welcome/register.html.erb</p>

app/views/zipcodes/_form.html.erb
<%= form_for(@zipcode) do |f| %>
  <% if @zipcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zipcode.errors.count, "error") %> prohibited this zipcode from being saved:</h2>

      <ul>
      <% @zipcode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :countOfCity %><br>
    <%= f.text_field :countOfCity %>
  </div>
  <div class="field">
    <%= f.label :cityStName %><br>
    <%= f.text_field :cityStName %>
  </div>
  <div class="field">
    <%= f.label :lastLineCity %><br>
    <%= f.text_field :lastLineCity %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :lat_degree %><br>
    <%= f.text_field :lat_degree %>
  </div>
  <div class="field">
    <%= f.label :lon_degree %><br>
    <%= f.text_field :lon_degree %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :areacode %><br>
    <%= f.text_field :areacode %>
  </div>
  <div class="field">
    <%= f.label :timeZoneLabel %><br>
    <%= f.text_field :timeZoneLabel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zipcodes/edit.html.erb
<h1>Editing zipcode</h1>

<%= render 'form' %>

<%= link_to 'Show', @zipcode %> |
<%= link_to 'Back', zipcodes_path %>

app/views/zipcodes/index.html.erb
<h1>Listing zipcodes</h1>

<table>
  <thead>
    <tr>
      <th>Details</th>
      <th>Zip</th>
      <th>Countofcity</th>
      <th>Citystname</th>
      <th>Lastlinecity</th>
      <th>State</th>
      <th>County</th>
      <th>Lat degree</th>
      <th>Lon degree</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Areacode</th>
      <th>Timezonelabel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zipcodes.each do |zipcode| %>
      <tr>
        <td><%= zipcode.details %></td>
        <td><%= zipcode.zip %></td>
        <td><%= zipcode.countOfCity %></td>
        <td><%= zipcode.cityStName %></td>
        <td><%= zipcode.lastLineCity %></td>
        <td><%= zipcode.state %></td>
        <td><%= zipcode.county %></td>
        <td><%= zipcode.lat_degree %></td>
        <td><%= zipcode.lon_degree %></td>
        <td><%= zipcode.lat %></td>
        <td><%= zipcode.long %></td>
        <td><%= zipcode.areacode %></td>
        <td><%= zipcode.timeZoneLabel %></td>
        <td><%= link_to 'Show', zipcode %></td>
        <td><%= link_to 'Edit', edit_zipcode_path(zipcode) %></td>
        <td><%= link_to 'Destroy', zipcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zipcode', new_zipcode_path %>

app/views/zipcodes/new.html.erb
<h1>New zipcode</h1>

<%= render 'form' %>

<%= link_to 'Back', zipcodes_path %>

app/views/zipcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Details:</strong>
  <%= @zipcode.details %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @zipcode.zip %>
</p>

<p>
  <strong>Countofcity:</strong>
  <%= @zipcode.countOfCity %>
</p>

<p>
  <strong>Citystname:</strong>
  <%= @zipcode.cityStName %>
</p>

<p>
  <strong>Lastlinecity:</strong>
  <%= @zipcode.lastLineCity %>
</p>

<p>
  <strong>State:</strong>
  <%= @zipcode.state %>
</p>

<p>
  <strong>County:</strong>
  <%= @zipcode.county %>
</p>

<p>
  <strong>Lat degree:</strong>
  <%= @zipcode.lat_degree %>
</p>

<p>
  <strong>Lon degree:</strong>
  <%= @zipcode.lon_degree %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @zipcode.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @zipcode.long %>
</p>

<p>
  <strong>Areacode:</strong>
  <%= @zipcode.areacode %>
</p>

<p>
  <strong>Timezonelabel:</strong>
  <%= @zipcode.timeZoneLabel %>
</p>

<%= link_to 'Edit', edit_zipcode_path(@zipcode) %> |
<%= link_to 'Back', zipcodes_path %>